# Generated by Django 5.2 on 2025-04-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productreview_rating_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
    ]
