# Generated by Django 5.2 on 2025-05-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_city_order_country_order_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('X', 'Canceled')], default='C', max_length=1),
        ),
    ]
