# Generated by Django 5.2 on 2025-04-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_profile_picture_userprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('seller', 'Seller')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
